services:
  server:
    build:
      dockerfile: Dockerfile
      target: server
    ports:
      - "3000:3000"
    networks:
      - internal
    environment:
      - SERVER_APP_URL=$SERVICE_FQDN_SERVER
  client:
    depends_on:
      - server
    build:
      dockerfile: Dockerfile
      target: client
    ports:
      - "8080:8080"
    networks:
      - internal
    environment:
      - CLIENT_APP_URL=$SERVICE_FQDN_CLIENT
      - SERVER_URL=$SERVICE_FQDN_SERVER
networks:
  internal:
    driver: bridge